### ISSUE TITLE
A question about the segmentation details

### ISSUE THREAD

**Issue by speedcell4** [bigganbing/Fairseq_MorphTE#1]
Hi, thanks for sharing the source code.

Just want to confirm a detail. According to this script, the morphology segmentation is performed on **subtoken**-level instead of **word**-level, is this correct?

https://github.com/bigganbing/Fairseq_MorphTE/blob/55e7541c98688204129b7db9262e74ebba96babf/mor_for_bpe_corpus_sep.py#L29-L32

**Comment by bigganbing** [comment]
> Hi, thanks for sharing the source code.
> 
> Just want to confirm a detail. According to this script, the morphology segmentation is performed on **subtoken**-level instead of **word**-level, is this correct?
> 
> https://github.com/bigganbing/Fairseq_MorphTE/blob/55e7541c98688204129b7db9262e74ebba96babf/mor_for_bpe_corpus_sep.py#L29-L32

That is true for the translation task which usually need to be processed by BPE. If BPE or other subtoken processing is not required for a task, the morphology segmentation can be performed on word-level.

**Comment by speedcell4** [comment]
Thanks~
